

import UIKit

let qs_tradeOwnerId = "tradeOwnerId"
let qs_tradeOwnerName = "tradeOwnerName"
let qs_toStoreName = "toStoreName"
let qs_consumptionSharePerDay = "consumptionSharePerDay"
let qs_latitude = "latitude"
let qs_longitude = "longitude"
let qs_location = "location"
let qs_date = "date"
let qs_time = "time"
let qs_lubeBrandStockShare = "lubeBrandStockShare"
let qs_lubeBrandStockShare1 = "lubeBrandStockShare1"
let qs_lubeBrandStockShare2 = "lubeBrandStockShare2"
let qs_lubeBrandStockShare3 = "lubeBrandStockShare3"
let qs_lubricantPercentage = "lubricantPercentage"
let qs_lubricantSoldPerDay = "lubricantSoldPerDay"
let qs_mechanicPainPoints = "mechanicPainPoints"
let qs_mechanicPainPoints_1 = "mechanicPainPoints_1"
let qs_mechanicPainPoints_2 = "mechanicPainPoints_2"
let qs_mechanicPainPoints_3 = "mechanicPainPoints_3"
let qs_mineral = "mineral"
let qs_nonLubricantPercentage = "nonLubricantPercentage"
let qs_noOfCarsServed = "noOfCarsServed"
let qs_numberOfMechanics = "numberOfMechanics"
let qs_quarter = "quarter"
let qs_satisfactionRating = "satisfactionRating"
let qs_semiSynthetic = "semiSynthetic"
let qs_service = "service"
let qs_service_1 = "service_1"
let qs_service_2 = "service_2"
let qs_service_3 = "service_3"
let qs_signageRemarks = "signageRemarks"
let qs_synthetic = "synthetic"
let qs_termsOfPayment = "termsOfPayment"
let qs_userId = "userId"
let qs_whoDoTheyBuyFrom = "whoDoTheyBuyFrom"
let qs_whoDoTheyBuyFrom_1 = "whoDoTheyBuyFrom_1"
let qs_whoDoTheyBuyFrom_2 = "whoDoTheyBuyFrom_2"
let qs_whoDoTheyBuyFrom_3 = "whoDoTheyBuyFrom_3"
let qs_year = "year"
let qs_lubeBrandDisplayShare = "lubeBrandDisplayShare"
let qs_merchandisingShare = "merchandisingShare"
let qs_physicalPicture = "physicalPicture"
let qs_signagePicture = "signagePicture"




let qs_otherServicesSelected = "otherServicesSelected"
let qs_otherPainPointSelected = "otherPainPointSelected"
let qs_otherBuyFromSelected = "otherBuyFromSelected"
let qs_otherPaymentsSelected = "otherPaymentsSelected"


let qs_otherServicesSelectedID = "otherServicesSelectedID"
let qs_otherPainPointSelectedID = "otherPainPointSelectedID"
let qs_otherBuyFromSelectedID = "otherBuyFromSelectedID"
let qs_otherPaymentsSelectedID = "otherPaymentsSelectedID"



let ws_tradeOwnerID = "tradeOwnwerId"
let ws_userId = "userId"
let ws_tradeOwnerName = "tradeOwnerName"
let ws_tradeOwnerStoreName = "tradeOwnerStoreName"
let ws_week = "week"
let ws_year = "year"
let ws_brandArray = "brandArray"
let ws_brandArrayLength = "brandArrayLength"

let ws_otherIDOne = "otherIDOne"
let ws_otherIDTwo = "otherIDTwo"
let ws_otherIDThree = "otherIDThree"
let ws_otherIDFour = "otherIDFour"
let ws_otherIDFive = "otherIDFive"

let ws_otherSelectedOne = "otherSelectedOne"
let ws_otherSelectedTwo = "otherSelectedTwo"
let ws_otherSelectedThree = "otherSelectedThree"
let ws_otherSelectedFour = "otherSelectedFour"
let ws_otherSelectedFive = "otherSelectedFive"

let ws_brandNameOne = "brandNameOne"
let ws_programPromoOne = "programPromoOne"
let ws_productImageDataOne = "productImageDataOne"
let ws_productImageOne = "productImageOne"
let ws_quantityOne = "quantityOne"
let ws_merchOfferOne = "merchOfferOne"
let ws_textFieldOne_a = "textFieldOne_a"
let ws_textFieldOne_b = "textFieldOne_b"
let ws_textFieldOne_c = "textFieldOne_c"

let ws_brandNameFive = "brandNameFive"
let ws_programPromoFive = "programPromoFive"
let ws_productImageDataFive = "productImageDataFive"
let ws_productImageFive = "productImageFive"
let ws_quantityFive = "quantityFive"
let ws_merchOfferFive = "merchOfferFive"
let ws_textFieldFive_a = "textFieldFive_a"
let ws_textFieldFive_b = "textFieldFive_b"
let ws_textFieldFive_c = "textFieldFive_c"

let ws_brandNameTwo = "brandNameTwo"
let ws_programPromoTwo = "programPromoTwo"
let ws_productImageDataTwo = "productImageDataTwo"
let ws_productImageTwo = "productImageTwo"
let ws_quantityTwo = "quantityTwo"
let ws_merchOfferTwo = "merchOfferTwo"
let ws_textFieldTwo_a = "textFieldTwo_a"
let ws_textFieldTwo_b = "textFieldTwo_b"
let ws_textFieldTwo_c = "textFieldTwo_c"

let ws_brandNameThree = "brandNameThree"
let ws_programPromoThree = "programPromoThree"
let ws_productImageDataThree = "productImageDataThree"
let ws_productImageThree = "productImageThree"
let ws_quantityThree = "quantityThree"
let ws_merchOfferThree = "merchOfferThree"
let ws_textFieldThree_a = "textFieldThree_a"
let ws_textFieldThree_b = "textFieldThree_b"
let ws_textFieldThree_c = "textFieldThree_c"

let ws_brandNameFour = "brandNameFour"
let ws_programPromoFour = "programPromoFour"
let ws_productImageDataFour = "productImageDataFour"
let ws_productImageFour = "productImageFour"
let ws_quantityFour = "quantityFour"
let ws_merchOfferFour = "merchOfferFour"
let ws_textFieldFour_a = "textFieldFour_a"
let ws_textFieldFour_b = "textFieldFour_b"
let ws_textFieldFour_c = "textFieldFour_c"

let ws_latitude = "latitude"
let ws_longitude = "longitude"
let ws_location = "location"
let ws_date = "date"
let ws_time = "time"


